### PR TITLE
Adds a crafting menu

### PR DESCRIPTION
**Pull request by Muncher2112**
Changes crafting from checking items in front of you, to a menu with graphics and recipes (similar to discordia)

Adds a few items with crafting recipes: Makeshift armor, helmets, beartraps, bandages, pistol, and more
Adds a few helpers 
All old recipe's are included, and they are still added the same way

### CODE REVIEW

**Comment by zamolxius** [comment]
oh wow this is  beautiful

**Comment by SireTurret** [comment]
is it possible to make the ingredient and tool list better so you can read it better?

**Comment by Muncher2112** [comment]
Should look better now.  Also if the recipe doesn't require a tool will show nothing instead of an empty "Tools:"

**Comment by SireTurret** [comment]
incredibly based, merging

**Pull request merged**
