### PR TITLE
Teeth fix and interrogation

### PR DESCRIPTION
**Pull request by Muncher2112**
- Fixes a bug with teeth initialization starting on humans instead of head organ, which gave people no teeth
- Made supreme arbiter never forget the prayer
- gives supreme arbiter a "interrogate" verb that forces heretics to out another random heretic, but only if they are in enough pain

### CODE REVIEW

**Comment by zamolxius** [comment]
this is brilliant

**Comment by SireTurret** [comment]
oh damn

**Comment by SireTurret** [comment]
i'll go remove the splint toxic made then

**Comment by SireTurret** [comment]
Merging, I guess.

**Pull request merged**
