### PR TITLE
Adds SEL OP to the jukebox

### PR DESCRIPTION
**Pull request by Muncher2112**
I like this song, and someone else requested it.  I can add more, because the current jukebox songs are pretty lame IMO

### CODE REVIEW

**Comment by SireTurret** [comment]
can you send a youtube link to it?

**Comment by Muncher2112** [comment]
https://www.youtube.com/watch?v=4-PkAQcuZOw

**Comment by SireTurret** [comment]
oh no an anime intro song!

but jokes aside I don't really care

**Comment by Muncher2112** [comment]
Just ignore this, I hate how git wants me to make different branches for each change.

**Pull request closed without merging**
