### PR TITLE
Succumb changes

### PR DESCRIPTION
**Pull request by Muncher2112**
People complained about dying being too difficult, it's because human "health" only factored in brainloss. Now it factors in all damage types. 

You can succumb at at "50" health, where 200 is full, 100 is unconscious, and 0 is stone dead.
You can also whisper below this threshold to whisper last worlds and succumb

### CODE REVIEW

**Comment by SireTurret** [comment]
>human health only factored in brainloss

Jesus christ.

**Comment by Muncher2112** [comment]
I hope that's correct, I'm always worried when tweaking health stuff.

**Comment by SireTurret** [comment]
I'll test this myself tomorrow unless you wish to do it yourself.

**Comment by Muncher2112** [comment]
I've tested it, seems to be working for me.

**Pull request merged**
